site:
  title: Magnolia Demo Docs Site
  # # the 404 page and sitemap files only get generated when the url property is set
  url: https://magnolia-demo-docs.netlify.app/
  start_page: home:ROOT:index.adoc
  robots: allow

content:
  sources:
  - url: .
    branches: HEAD
    start_paths:
      - home


urls:
  html_extension_style: indexify

ui:
  bundle:
    url: https://github.com/alex-at-magnolia/demo-docs-ui/files/7548651/ui-bundle.zip
    snapshot: true

# Global asciidoc attributes here
asciidoc:
  attributes:
    page-pagination: true
    check-mark: '&#x2714;'
    kroki-fetch-diagram: true
    figure-caption!:
    magnolia: https://www.magnolia-cms.com
    jira: https://jira.magnolia-cms.com/browse/
    mla: link:https://www.magnolia-cms.com/mla.html[MLA^]
    gpl: link:http://www.gnu.org/licenses/gpl-3.0.html[GPL^]
    company: Magnolia
    magnolia-latest-version: 6.2.13
    demo-docs-git: https://github.com/alex-at-magnolia/demo-docs.git
    ps-netlify-link: https://app.netlify.com/teams/magnolia-services/overview
    demo-docs-repo: https://github.com/alex-at-magnolia/demo-docs
  extensions:
  - ./lib/tabs-block.js
  - asciidoctor-kroki
