= {project}

// just styles for the iframes
include::partial$styles.adoc[]

This site is here to provide you with information on our Magnolia e-commerce demo site. We hope to provide you with a good understanding of each of demo pages as well as what Magnolia modules make up that particular page.

icon:cog[spin] This page is a _work in progress_ as of {localdate}. Please bear with us while we continue to improve the site.

[cols="3s,7a"]
|===
|Site |URL

|Live
|link:https://ecommerce-headless-public.magnolia-cms-demo.com/home/[^]

|Author
|link:http://ecommerce-headless-author.magnolia-cms-demo.com/[^]

|Public
|link:https://ecommerce-headless-public.magnolia-cms-demo.com/[^]

|Source repository (`git`)
|link:https://git.magnolia-cms.com/projects/DEMOS/repos/services-demos-common/browse[^]

|===

NOTE: The sections below provide you with a quick view into the site page and lists the modules that contribute to building the page.

== Home page

++++
<iframe src="https://ecommerce-headless-public.magnolia-cms-demo.com/home/" title="Magnolia e-commerce demo page"></iframe>
++++


// features
:features: carousel,color-picker,campaign-manager,attraqt,component-personalization
include::partial$r_magnolia-features.adoc[leveloffset=+2]

== Subpages

The subpages consist of the *Living*, *Dining*, *Bathroom*, and *Garden* pages.

NOTE: The page previewed below is the *Living* page.

++++
<iframe src="https://ecommerce-headless-public.magnolia-cms-demo.com/home/living" title="Magnolia e-commerce demo page"></iframe>
++++

// features
:features: commercetools,filtering
include::partial$r_magnolia-features.adoc[leveloffset=+2]

== Inspirations page

++++
<iframe src="https://ecommerce-headless-public.magnolia-cms-demo.com/home/inspirations" title="Magnolia e-commerce demo page"></iframe>
++++

// features
:features: commercetools,filtering
include::partial$r_magnolia-features.adoc[leveloffset=+2]

== Blog

++++
<iframe src="https://ecommerce-headless-public.magnolia-cms-demo.com/home/blog" title="Magnolia e-commerce demo page"></iframe>
++++

// features
:features: stories-app,focal-hotspot
include::partial$r_magnolia-features.adoc[leveloffset=+2]

== Events page

++++
<iframe src="https://ecommerce-headless-public.magnolia-cms-demo.com/home/events" title="Magnolia e-commerce demo page"></iframe>
++++

// features
:features: content-type
include::partial$r_magnolia-features.adoc[leveloffset=+2]

== Poll

++++
<iframe src="https://ecommerce-headless-public.magnolia-cms-demo.com/home/poll" title="Magnolia e-commerce demo page"></iframe>
++++

// features
:features: poll
include::partial$r_magnolia-features.adoc[leveloffset=+2]

== Other features

// features
:features: others
include::partial$r_magnolia-features.adoc[leveloffset=+2]

:features: reset
